/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 spaceman.glb
Author: likesenape (https://sketchfab.com/likesenape)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spaceman-model-4494aa9be0c84b9dbef590a588b493cf
Title: Spaceman Model
*/

import React, {useLayoutEffect, useRef} from 'react'
import {useGLTF, useAnimations, useScroll} from '@react-three/drei'
import {useFrame} from "@react-three/fiber";
import gsap from "gsap";
import { MeshStandardMaterial } from 'three';

export function Spaceman(props) {
  const robot = useRef()
  const { nodes, materials, animations } = useGLTF('./models/spaceman/spaceman.glb')

  const scroll = useScroll()
  const tl = useRef()

  useFrame((state, delta)=>{
    tl.current.seek(scroll.offset * tl.current.duration())
  })

  useLayoutEffect(()=> {
    tl.current = gsap.timeline({defaults: {duration: 2, ease: 'power1.inOut'}})

    tl.current
        .to(robot.current.rotation, {y: -1}, 2)
        .to(robot.current.position, {x: 1}, 2)

        .to(robot.current.rotation, {y: 1}, 6)
        .to(robot.current.position, {x: -1}, 6)

        .to(robot.current.rotation, {y: 0}, 11)
        .to(robot.current.rotation, {x: 1}, 11)
        .to(robot.current.position, {x: 0}, 11)

        .to(robot.current.rotation, {y: 0}, 20)
        .to(robot.current.rotation, {x: 0}, 20)
        .to(robot.current.position, {x: 0}, 20)

  },[])


  const spacemanPaint = new MeshStandardMaterial({
    envMapIntensity: 1,
    color: '#ececec',
    metalness: 1,
    roughness: .5,
  });

  const spacemanDark = new MeshStandardMaterial({
    envMapIntensity: 1,
    color: '#020202',
    metalness: 1,
    roughness: .1,
  });

  const spacemanMetal = new MeshStandardMaterial({
    envMapIntensity: 1,
    color: '#fae3dc',
    metalness: .5,
    roughness: .8,
  });

  return (
    <group position={[0, -2, 0]} rotation={[0, 0, 0]} scale={1} dispose={null} ref={robot}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Empty" position={[0.048, 1.382, 4.313]} scale={9.823}>
              <group name="Spot005" position={[0.343, -1.563, -0.005]} rotation={[1.592, 0.184, -1.15]} scale={0.102}>
                <group name="Spot005_1" />
              </group>
              <group name="Sun002" position={[0.507, 0.554, 3.164]} rotation={[-0.171, 0.128, -0.32]} scale={0.102}>
                <group name="Sun002_1" />
              </group>
              <group name="Spot009" position={[0.9, 0.536, 0.569]} rotation={[-0.628, 0.798, 0.968]} scale={0.102}>
                <group name="Spot009_1" />
              </group>
              <group name="Spot008" position={[-1.025, -0.622, 0.423]} rotation={[0.488, -0.649, -2.185]} scale={0.102}>
                <group name="Spot008_1" />
              </group>
            </group>
            <group name="Sphere007">
              <mesh name="Sphere007_0" geometry={nodes.Sphere007_0.geometry} material={spacemanPaint} />
            </group>
            <group name="NurbsPath004" position={[0.632, 0.09, 4.163]} rotation={[-0.526, -0.213, -1.309]} scale={0.355}>
              <mesh name="NurbsPath004_0" geometry={nodes.NurbsPath004_0.geometry} material={spacemanPaint} />
            </group>
            <group name="Plane005" position={[0.099, 2.147, 3.085]} rotation={[1.593, -0.01, 0.019]} scale={[0.786, 1.012, 1.012]}>
              <mesh name="Plane005_0" geometry={nodes.Plane005_0.geometry} material={spacemanPaint} />
            </group>
            <group name="Cylinder002" position={[0.113, 1.496, 3.313]} rotation={[0.022, -0.019, -0.01]} scale={0.867}>
              <mesh name="Cylinder002_0" geometry={nodes.Cylinder002_0.geometry} material={spacemanPaint} />
            </group>
            <group name="Plane006">
              <mesh name="Plane006_0" geometry={nodes.Plane006_0.geometry} material={spacemanPaint} />
            </group>
            <group name="Sphere008" position={[0.108, 1.44, 3.194]} rotation={[0.022, -0.019, -0.01]} scale={0.918}>
              <mesh name="Sphere008_0" geometry={nodes.Sphere008_0.geometry} material={spacemanPaint} />
              <mesh name="Sphere008_1" geometry={nodes.Sphere008_1.geometry} material={spacemanDark} />
            </group>
            <group name="Sphere009">
              <mesh name="Sphere009_0" geometry={nodes.Sphere009_0.geometry} material={spacemanPaint} />
              <mesh name="Sphere009_0_1" geometry={nodes.Sphere009_0_1.geometry} material={spacemanPaint} />
              <mesh name="Sphere009_0_2" geometry={nodes.Sphere009_0_2.geometry} material={spacemanPaint} />
              <mesh name="Sphere009_0_3" geometry={nodes.Sphere009_0_3.geometry} material={spacemanPaint} />
              <mesh name="Sphere009_0_4" geometry={nodes.Sphere009_0_4.geometry} material={spacemanPaint} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/spaceman/spaceman.glb')
